### ISSUE TITLE
Not working on my RG35XX

### ISSUE THREAD

**Issue by JamesIV4** [hagibr/RG35XX#1]
I followed the instructions in the readme:

> Copy the PYAPPS folder to your SDCARD/Roms folder
> Change /CFW/config/coremapping.json (ROMS partition) by adding the line at the end of the list
> "PYAPPS": "/bin/sh",

But all the included sample files crash immediately. Any idea what could be missing here?

I'm working on a search app with pygame and python.

**Comment by hagibr** [comment]
Hello, I am happy that someone else is working on development of Python apps.
Are you having the same behavior when you run 'wait10.sh', 'wait5.sh'? They aren't invoking python interpretor, they are just for stalling GarlicOS while I run my tests on the adb shell.

**Comment by JamesIV4** [comment]
Yes, same behavior. I noticed the paths might be off by exporting the output log to a file.

I was able to hack my script into launching by just hardcoding the path:
```
#!/bin/sh
SCRIPT_DIR=$(busybox dirname "$0")
PYTHONPATH=${SCRIPT_DIR}/Python
HOME=${SCRIPT_DIR}/Search
PROG_PATH=/mnt/mmc/Roms/PYAPPS/Search/Search.py
cd ${PYTHONPATH}
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(busybox pwd)/lib
./python3.10 ${PROG_PATH} > search.log 2>&1
sync
```

Apparently ` > search.log 2>&1` outputs to a log file that shows up in the Python folder. (Thanks ChatGPT)
Now I have errors finding SDL 1.2, but at least it's running the python script.

My current issue:
```
Traceback (most recent call last):
  File "/mnt/mmc/Roms/PYAPPS/Search/Search.py", line 1, in <module>
    import pygame
  File "/mnt/mmc/Roms/PYAPPS/Python/lib/python3.10/site-packages/pygame/__init__.py", line 133, in <module>
    from pygame.base import *
ImportError: /usr/lib/libSDL-1.2.so.0: internal error
```

I tried similar changes in the other example shell scripts and can't get them to launch or even make a log file.

For my project, I might abandon pygame and find something python related that's even more barebones, or just code it in SDL directly.

**Comment by JamesIV4** [comment]
OK... I'm not sure what I did wrong before, but your original script is working for me now. May not be a path issue after all.

**Comment by hagibr** [comment]
For debugging purposes, you can use the '.exec_script_in_adb.sh':
Access your device using adb shell and run:

```
cd /mnt/SDCARD/Roms/PYAPPS
./.exec_script_in_adb.sh search.sh
```

This is the way I use in my workflow. If it's something that draw something in the screen, first I run one of the 'waitX.sh' on GarlicOS then I run this script.

**Comment by JamesIV4** [comment]
I'll definitely try that

**Comment by JamesIV4** [comment]
Sorry to turn this into a support thread for my work, but I have enableADB in MISC and am connected over USB, and using the adb.exe tool from the Android SDK, I am not seeing any devices connected.

**Comment by hagibr** [comment]
No problem. Maybe you still need to install some driver. I think you can find something useful here: https://developer.android.com/studio/run/win-usb
